//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int IdComanda { get; set; }

        public int IdPlato { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Comanda Comanda { get; set; }
        public virtual Plato Plato { get; set; }
    }
}
